openapi: 3.0.0
info:
  title: Movie Database API
  version: 1.0.0
  description: |
    A comprehensive API for managing movies and user favorites with:
    - JWT Authentication
    - Role-based access control
    - Redis caching
    - Sorting and rating capabilities

servers:
  - url: http://localhost:5000
    description: Local development server

paths:
  /movies:
    get:
      summary: Get popular movies
      tags:
        - Movies
      responses:
        '200':
          description: List of popular movies
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 123
                        title:
                          type: string
                          example: "Inception"
                        release_date:
                          type: string
                          format: date
                          example: "2023-01-15"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /users/{user_id}/favorites:
    post:
      summary: Add a movie to favorites
      tags: [Favorites]
      security:
        - bearerAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [id, title, release_date]
              properties:
                id:
                  type: integer
                  example: 123
                title:
                  type: string
                  example: "The Dark Knight"
                release_date:
                  type: string
                  format: date
                  example: "2023-05-20"
      responses:
        '201':
          description: Movie added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Movie added to favorites"
                  data:
                    $ref: '#/components/schemas/Movie'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      summary: Get sorted favorite movies
      tags: [Favorites]
      security:
        - bearerAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            example: 1
        - name: sort_by
          in: query
          description: Comma-separated list of sorting fields (release_date, rating)
          schema:
            type: string
            default: "release_date,rating"
      responses:
        '200':
          description: List of favorite movies
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/FavoriteMovie'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /users/{user_id}/favorites/{movie_id}:
    delete:
      summary: Remove a movie from favorites
      tags: [Favorites]
      security:
        - bearerAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            example: 1
        - name: movie_id
          in: path
          required: true
          schema:
            type: integer
            example: 123
      responses:
        '200':
          description: Movie removed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Movie 123 removed from favorites"
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    patch:
      summary: Update movie rating
      tags: [Favorites]
      security:
        - bearerAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            example: 1
        - name: movie_id
          in: path
          required: true
          schema:
            type: integer
            example: 123
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [rating]
              properties:
                rating:
                  type: integer
                  minimum: 0
                  maximum: 5
                  example: 4
      responses:
        '200':
          description: Rating updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Rating for movie 123 updated to 4"
        '400':
          description: Invalid rating
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /admin/users/{user_id}/favorites:
    delete:
      summary: Remove all favorites for a user (Admin only)
      tags: [Admin]
      security:
        - bearerAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            example: 2
      responses:
        '200':
          description: Favorites cleared
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "All favorites for user 2 removed"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Movie:
      type: object
      properties:
        id:
          type: integer
          example: 123
        title:
          type: string
          example: "Inception"
        release_date:
          type: string
          format: date
          example: "2023-05-20"
        rating:
          type: integer
          example: 0

    FavoriteMovie:
      type: object
      properties:
        movie_id:
          type: integer
          example: 123
        release_date:
          type: string
          format: date
          example: "2023-05-20"
        rating:
          type: integer
          example: 4

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          example: "Invalid rating value"